title: Jerome Swannack
email: jeromeswannack@gmail.com
description: >-
  Documentation of miscellaneous projects by Jerome Swannack
baseurl: ""
url: "http://www.jeromeswannack.com" # TODO: set up https
github_username: jerome3o

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-analytics

collections:
  - books
  - hikes
  - projects
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Other configuration settings
analytics:
  provider: google
  google:
    tracking_id: G-CN46CDLGFM
